[workspace]
channels = ["conda-forge", "bioconda"]
name = "NUMT_detection"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.10.*"
biopython = ">=1.86,<2"
cyvcf2 = ">=0.31.1,<0.32"
pandas = ">=2.3.3,<3"
portion = ">=2.6.1,<3"
pybedtools = ">=0.10.0,<0.11"
snakemake = "7.*"
bcftools = ">=1.21,<2"
blast = "2.14.0.*"
ucsc-liftover = ">=469,<470"
vcflib = "1.0.10.*"
networkx = ">=3.4.2,<4"
bedtools = ">=2.31.1,<3"
csvtk = ">=0.36.0,<0.37"
